#ifndef ERROR_HANDLING_H
#define ERROR_HANDLING_H

typedef enum pml_err_t {
    PML_OK = 0,
    PML_WRONG_TYPE = 1,
    PML_OUT_OF_MEMORY = 2,
    PML_OUT_OF_BOUNDS = 3,
    PML_EMPTY_TENSOR = 4,
    PML_INCORRECT_INPUT = 5,
    PML_TENSORS_NOT_BROADCASTABLE = 6,
    PML_TENSOR_NOT_CONTIGUOUS = 7,
} pml_err_t;

#endif // ERROR_HANDLING_H
